version: "2"
services:

  plana:
    build: .
    tty: true
    volumes: 
      - ./plana:/var/www/html
    ports:
      - 80:80
      - 8000:8000
    container_name: plana_planOS
   
  mysql:
    image: mysql:5.5
    volumes:
    -  ./data/mysql:/var/lib/mysql 
    - ./data/my.cnf:/etc/mysql/conf.d/my.cnf
    - ./data/init/:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: php1850
      MYSQL_DATABASE: planasphere
    #command: ["/docker-entrypoint-initdb.d"]
    container_name: Db